standalone: improve virtual device creation errors (#632)
Currently, many of the error messages reported by `propolis-standalone`
when creating a virtual device don't provide a lot of information
describing the error that occurred. None of these errors include the
device name or driver of the device that could not be created.
Furthermore, errors when creating a VioNA virtio device don't include
the name of the VNIC that we attempted to connect to, which is also
useful information for debugging errors. See #612 for a motivating
example of an unhelpful error message.

This branch adds improved error contexts and logging to
`propolis-standalone`'s virtual device creation. In particular, I've
done the following:

- Wrapped the entire virtual device creation in a closure and added an
  `anyhow` error context with the name of the device and the driver, so
  that it's clearer what device couldn't be created.
- Wrapped the call to `PciVirtioViona::new` with an `anyhow` error
  context that includes the name of the VNIC we are attempting to use
- Added a `DEBUG`-level log line for every virtual device we attempt to
  create
- Improved the log line for unrecognized drivers to actually include the
  name of the driver that we didn't know about.

To compare the error messages on this branch with the error messages on
`master`, here's the output I get when I create a VM with VNIC that
doesn't exist, like:

```toml
[dev.net0]
driver = "pci-virtio-viona"
vnic = "fake-vnic0"
pci-path = "0.5.0"
```

On `master`, I get the following output:

```console
eliza@atrium ~/propolis $ pfexec cargo run -p propolis-standalone -- testvm.toml
    Finished dev [unoptimized + debuginfo] target(s) in 0.35s
     Running `target/debug/propolis-standalone testvm.toml`
Jan 29 20:21:02.152 INFO Creating VM with 4 vCPUs, 1073741824 lowmem, 0 highmem
Jan 29 20:21:02.638 INFO VM created, name: testvm
Error: DLADM_STATUS_NOTFOUND
```

On this branch, the output is much more helpful:

```console
eliza@atrium ~/propolis $ pfexec cargo run -p propolis-standalone -- testvm.toml
    Finished dev [unoptimized + debuginfo] target(s) in 0.34s
     Running `target/debug/propolis-standalone testvm.toml`
Jan 29 21:01:59.337 INFO Creating VM with 4 vCPUs, 1073741824 lowmem, 0 highmem
Jan 29 21:01:59.819 INFO VM created, name: testvm
Error: Failed to create pci-virtio-viona device 'net0'

Caused by:
    0: Failed to connect to VioNA VNIC 'fake-vnic0'
    1: DLADM_STATUS_NOTFOUND
```

Closes #612